/* eslint-disable */

// @ts-nocheck

// This file was automatically generated by @caffeinelabs/bindgen@0.1.0-beta.9.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { IDL } from '@icp-sdk/core/candid';

export const Video = IDL.Record({
  'url' : IDL.Text,
  'title' : IDL.Text,
  'thumbnail' : IDL.Text,
  'description' : IDL.Text,
  'category' : IDL.Text,
});
export const UserRole = IDL.Variant({
  'admin' : IDL.Null,
  'user' : IDL.Null,
  'guest' : IDL.Null,
});
export const VideoCategory = IDL.Record({
  'name' : IDL.Text,
  'videos' : IDL.Vec(Video),
});
export const UserProfile = IDL.Record({ 'name' : IDL.Text });
export const Message = IDL.Record({
  'id' : IDL.Nat,
  'content' : IDL.Text,
  'sender' : IDL.Text,
  'language' : IDL.Text,
});
export const http_header = IDL.Record({
  'value' : IDL.Text,
  'name' : IDL.Text,
});
export const http_request_result = IDL.Record({
  'status' : IDL.Nat,
  'body' : IDL.Vec(IDL.Nat8),
  'headers' : IDL.Vec(http_header),
});
export const TransformationInput = IDL.Record({
  'context' : IDL.Vec(IDL.Nat8),
  'response' : http_request_result,
});
export const TransformationOutput = IDL.Record({
  'status' : IDL.Nat,
  'body' : IDL.Vec(IDL.Nat8),
  'headers' : IDL.Vec(http_header),
});

export const idlService = IDL.Service({
  'addVideo' : IDL.Func([Video], [], []),
  'addVideoCategory' : IDL.Func([IDL.Text], [], []),
  'assignCallerUserRole' : IDL.Func([IDL.Principal, UserRole], [], []),
  'fetchAllPublicTEDVideos' : IDL.Func([], [IDL.Text], []),
  'fetchBusinessTEDVideos' : IDL.Func([], [IDL.Text], []),
  'fetchMarketData' : IDL.Func([], [IDL.Text], []),
  'getAllVideoCategories' : IDL.Func([], [IDL.Vec(VideoCategory)], ['query']),
  'getCallerUserProfile' : IDL.Func([], [IDL.Opt(UserProfile)], ['query']),
  'getCallerUserRole' : IDL.Func([], [UserRole], ['query']),
  'getRecentMessages' : IDL.Func(
      [IDL.Principal, IDL.Nat],
      [IDL.Vec(Message)],
      ['query'],
    ),
  'getUserProfile' : IDL.Func(
      [IDL.Principal],
      [IDL.Opt(UserProfile)],
      ['query'],
    ),
  'getVideoCategory' : IDL.Func(
      [IDL.Text],
      [IDL.Opt(VideoCategory)],
      ['query'],
    ),
  'getVideosByCategory' : IDL.Func(
      [IDL.Text],
      [IDL.Opt(IDL.Vec(Video))],
      ['query'],
    ),
  'initializeAccessControl' : IDL.Func([], [], []),
  'isCallerAdmin' : IDL.Func([], [IDL.Bool], ['query']),
  'saveCallerUserProfile' : IDL.Func([UserProfile], [], []),
  'sendEnglishMessage' : IDL.Func([IDL.Text], [Message], []),
  'sendMarketQuery' : IDL.Func([IDL.Text], [Message], []),
  'sendMessage' : IDL.Func([IDL.Text, IDL.Text], [Message], []),
  'sendSwahiliMessage' : IDL.Func([IDL.Text], [Message], []),
  'sendUSSDRequest' : IDL.Func([IDL.Text, IDL.Text], [IDL.Text], []),
  'transform' : IDL.Func(
      [TransformationInput],
      [TransformationOutput],
      ['query'],
    ),
  'updateVideoThumbnail' : IDL.Func([IDL.Text, IDL.Text, IDL.Text], [], []),
});

export const idlInitArgs = [];

export const idlFactory = ({ IDL }) => {
  const Video = IDL.Record({
    'url' : IDL.Text,
    'title' : IDL.Text,
    'thumbnail' : IDL.Text,
    'description' : IDL.Text,
    'category' : IDL.Text,
  });
  const UserRole = IDL.Variant({
    'admin' : IDL.Null,
    'user' : IDL.Null,
    'guest' : IDL.Null,
  });
  const VideoCategory = IDL.Record({
    'name' : IDL.Text,
    'videos' : IDL.Vec(Video),
  });
  const UserProfile = IDL.Record({ 'name' : IDL.Text });
  const Message = IDL.Record({
    'id' : IDL.Nat,
    'content' : IDL.Text,
    'sender' : IDL.Text,
    'language' : IDL.Text,
  });
  const http_header = IDL.Record({ 'value' : IDL.Text, 'name' : IDL.Text });
  const http_request_result = IDL.Record({
    'status' : IDL.Nat,
    'body' : IDL.Vec(IDL.Nat8),
    'headers' : IDL.Vec(http_header),
  });
  const TransformationInput = IDL.Record({
    'context' : IDL.Vec(IDL.Nat8),
    'response' : http_request_result,
  });
  const TransformationOutput = IDL.Record({
    'status' : IDL.Nat,
    'body' : IDL.Vec(IDL.Nat8),
    'headers' : IDL.Vec(http_header),
  });
  
  return IDL.Service({
    'addVideo' : IDL.Func([Video], [], []),
    'addVideoCategory' : IDL.Func([IDL.Text], [], []),
    'assignCallerUserRole' : IDL.Func([IDL.Principal, UserRole], [], []),
    'fetchAllPublicTEDVideos' : IDL.Func([], [IDL.Text], []),
    'fetchBusinessTEDVideos' : IDL.Func([], [IDL.Text], []),
    'fetchMarketData' : IDL.Func([], [IDL.Text], []),
    'getAllVideoCategories' : IDL.Func([], [IDL.Vec(VideoCategory)], ['query']),
    'getCallerUserProfile' : IDL.Func([], [IDL.Opt(UserProfile)], ['query']),
    'getCallerUserRole' : IDL.Func([], [UserRole], ['query']),
    'getRecentMessages' : IDL.Func(
        [IDL.Principal, IDL.Nat],
        [IDL.Vec(Message)],
        ['query'],
      ),
    'getUserProfile' : IDL.Func(
        [IDL.Principal],
        [IDL.Opt(UserProfile)],
        ['query'],
      ),
    'getVideoCategory' : IDL.Func(
        [IDL.Text],
        [IDL.Opt(VideoCategory)],
        ['query'],
      ),
    'getVideosByCategory' : IDL.Func(
        [IDL.Text],
        [IDL.Opt(IDL.Vec(Video))],
        ['query'],
      ),
    'initializeAccessControl' : IDL.Func([], [], []),
    'isCallerAdmin' : IDL.Func([], [IDL.Bool], ['query']),
    'saveCallerUserProfile' : IDL.Func([UserProfile], [], []),
    'sendEnglishMessage' : IDL.Func([IDL.Text], [Message], []),
    'sendMarketQuery' : IDL.Func([IDL.Text], [Message], []),
    'sendMessage' : IDL.Func([IDL.Text, IDL.Text], [Message], []),
    'sendSwahiliMessage' : IDL.Func([IDL.Text], [Message], []),
    'sendUSSDRequest' : IDL.Func([IDL.Text, IDL.Text], [IDL.Text], []),
    'transform' : IDL.Func(
        [TransformationInput],
        [TransformationOutput],
        ['query'],
      ),
    'updateVideoThumbnail' : IDL.Func([IDL.Text, IDL.Text, IDL.Text], [], []),
  });
};

export const init = ({ IDL }) => { return []; };