/* eslint-disable */

// @ts-nocheck

// This file was automatically generated by @caffeinelabs/bindgen@0.1.0-beta.9.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import type { ActorMethod } from '@icp-sdk/core/agent';
import type { IDL } from '@icp-sdk/core/candid';
import type { Principal } from '@icp-sdk/core/principal';

export interface Message {
  'id' : bigint,
  'content' : string,
  'sender' : string,
  'language' : string,
}
export interface TransformationInput {
  'context' : Uint8Array,
  'response' : http_request_result,
}
export interface TransformationOutput {
  'status' : bigint,
  'body' : Uint8Array,
  'headers' : Array<http_header>,
}
export interface UserProfile { 'name' : string }
export type UserRole = { 'admin' : null } |
  { 'user' : null } |
  { 'guest' : null };
export interface Video {
  'url' : string,
  'title' : string,
  'thumbnail' : string,
  'description' : string,
  'category' : string,
}
export interface VideoCategory { 'name' : string, 'videos' : Array<Video> }
export interface http_header { 'value' : string, 'name' : string }
export interface http_request_result {
  'status' : bigint,
  'body' : Uint8Array,
  'headers' : Array<http_header>,
}
export interface _SERVICE {
  'addVideo' : ActorMethod<[Video], undefined>,
  'addVideoCategory' : ActorMethod<[string], undefined>,
  'assignCallerUserRole' : ActorMethod<[Principal, UserRole], undefined>,
  'fetchAllPublicTEDVideos' : ActorMethod<[], string>,
  'fetchBusinessTEDVideos' : ActorMethod<[], string>,
  'fetchMarketData' : ActorMethod<[], string>,
  'getAllVideoCategories' : ActorMethod<[], Array<VideoCategory>>,
  'getCallerUserProfile' : ActorMethod<[], [] | [UserProfile]>,
  'getCallerUserRole' : ActorMethod<[], UserRole>,
  'getRecentMessages' : ActorMethod<[Principal, bigint], Array<Message>>,
  'getUserProfile' : ActorMethod<[Principal], [] | [UserProfile]>,
  'getVideoCategory' : ActorMethod<[string], [] | [VideoCategory]>,
  'getVideosByCategory' : ActorMethod<[string], [] | [Array<Video>]>,
  'initializeAccessControl' : ActorMethod<[], undefined>,
  'isCallerAdmin' : ActorMethod<[], boolean>,
  'saveCallerUserProfile' : ActorMethod<[UserProfile], undefined>,
  'sendEnglishMessage' : ActorMethod<[string], Message>,
  'sendMarketQuery' : ActorMethod<[string], Message>,
  'sendMessage' : ActorMethod<[string, string], Message>,
  'sendSwahiliMessage' : ActorMethod<[string], Message>,
  'sendUSSDRequest' : ActorMethod<[string, string], string>,
  'transform' : ActorMethod<[TransformationInput], TransformationOutput>,
  'updateVideoThumbnail' : ActorMethod<[string, string, string], undefined>,
}
export declare const idlService: IDL.ServiceClass;
export declare const idlInitArgs: IDL.Type[];
export declare const idlFactory: IDL.InterfaceFactory;
export declare const init: (args: { IDL: typeof IDL }) => IDL.Type[];